spring:
  application:
    name: cloud-upload
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

server:
  port: 9005

management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9001/oauth/token
      user-authorization-uri: http://localhost:9001/oauth/authorize
    resource:
      token-info-uri: http://localhost:9001/oauth/check_token
