spring:
  application:
    name: business-reg
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848

dubbo:
  scan:
    base-packages: com.wzh.myshop.plus.business.reg.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: spring-cloud://192.168.1.100

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
